# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'daohang' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for daohang
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  # `pod 'react-native-video', :path => '../node_modules/react-native-video/react-native-video.podspec'`
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  # `pod 'react-native-video/VideoCaching', :path => '../node_modules/react-native-video/react-native-video.podspec'`
end
